people/config/routes.rb
Rails.application.routes.draw do

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
#root to: 'users#new'

get 'friend', to: 'users#friend', as: 'friend'
get 'neutrality', to: 'users#neutrality', as: 'neutrality'
get 'enemy', to: 'users#enemy', as: 'enemy'


  get "log_out" => "sessions#destroy", :as => "log_out"
	get "log_in" => "sessions#new", :as => "log_in"
	get "sign_up" => "users#new", :as => "sign_up"
	get "account/:id" => "users#edit", :as => "account"

  get 'sessions/new'
  root :to => "sessions#new"
	resources :sessions

#get 'persons/profile', as: 'user_root'

resources :users
resources :enemys, controller: :users
resources :friends
resources :neutrality

devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

people/app/models/enemy.rb
class Enemy < User
 before_action :authenticate_user!
end

people/app/models/friend.rb
class Friend < User
 before_action :authenticate_user!
end

people/app/models/log.rb
class Log < ApplicationRecord
end

people/app/models/neutrality.rb
class Neutrality < User
 before_action :authenticate_user!  
end

people/app/models/user.rb
class User < ApplicationRecord
   validates :name, presence: true

  devise :omniauthable, omniauth_providers: [:google_oauth2]


   def self.authenticate(name, password)
		user = find_by_name(name)
		if user && user.password == password
      user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password = password
		end
	end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    # unless user
    #     user = User.create(name: data['name'],
    #        email: data['email'],
    #        password: Devise.friendly_token[0,20]
    #     )
    # end
    user
end

end

people/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # before_action :authenticate_user!

  helper_method :current_user

	private

	def current_user
	  @current_user ||= User.find(session[:id]) if session[:id]
	end

  protected def authenticate_user!
       unless current_user
       store_location_for(:user, request.url)
       redirect_to new_session_url
     end
   end
end

people/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
end

people/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
	  user = User.authenticate(params[:name], params[:password])
	  if user
		session[:id] = user.id
		redirect_to users_url, :notice => "Logged in!"
	  else
		flash.now.alert = "Invalid first_name or password"
		render 'new'
	  end
	end

	def destroy
		session[:id] = nil
		redirect_to root_url, :notice => "Logged out!"

	end

end

people/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

people/app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
  # http_basic_authenticate_with name before_filter :authenticate_user!

  def index
       @user = User.paginate(page: params[:page], per_page: 12)
  end

  def new
      @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def friend
    @friend = Friend.paginate(page: params[:page], per_page: 12)

  end
  def neutrality
    @neutrality = Neutrality.paginate(page: params[:page], per_page: 12)
  end

  def enemy
    @enemy = Enemy.paginate(page: params[:page], per_page: 12)
  end

  def update
    if params[:neutrality]
      ServiceLog.new(neutrality_params).userUpdate
    elsif params[:friend]
      ServiceLog.new(friend_params).userUpdate
    elsif params[:enemy]
      ServiceLog.new(enemy_params).userUpdate
    else
    end
    redirect_to users_path
        # render plain: params[:neutrality].inspect
  end

  def create
#    User.transaction do
    ServiceLog.new(user_params).userCreate
#   if @user.save
       redirect_to users_path
#     else
#        render 'new'
#     end
  end

  def destroy
      #render plain: params[:user].inspect
      ServiceDel.new(params[:id]).userDestroy
      redirect_to users_path
  end

  private def people_params
    params.require(:user).permit(:id, :name, :name_before, :type, :type_before)
  end
  def neutrality_params
    params.require(:neutrality).permit(:id, :name, :name_before, :type, :type_before)
  end
  def friend_params
    params.require(:friend).permit(:id, :name, :name_before, :type, :type_before)
  end
  def enemy_params
    params.require(:enemy).permit(:id, :name, :name_before, :type, :type_before)
  end

  def user_params
    params.require(:user).permit(:name, :type)
  end


end

people/app/helpers/friends_helper.rb
module FriendsHelper
end

people/app/views/users/_form.html.erb
<article class="people">
  <section class="people-head">
    <% if @user.errors.any?  %>
       <div class="alert alert-danger">
           <h2>
             <%= pluralize(@user.errors.count, "error") %>
           </h2>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
     <% end %>

    <%= form_for @user , url: user_path(@user)  do |f| %>
      <p>
        <%= f.label :name %> <br>
        <%= f.text_field :name %>
        <%= f.hidden_field :name_before, :value => @user.name %>
      </p>
      <p>
        <%= f.hidden_field :type_before, :value => @user.type %>
        <%= f.label :type%> <br>
        <%= f.hidden_field :id, :value => @user.id %>

        <% if @user.type == 'Friend' %>
          <%= f.select(:type, options_for_select([['Friend', 'Friend'], ['Neutrality', 'Neutrality']], selected: f.object.type), include_blank: true)%>
        <% end %>

        <% if @user.type == 'Enemy' %>
          <%= f.select(:type, options_for_select([['Enemy', 'Enemy'], ['Neutrality', 'Neutrality']], selected: f.object.type), include_blank: true)%>
        <% end %>

        <% if @user.type == 'Neutrality' %>
          <%= f.select(:type, options_for_select([['Friend', 'Friend'], ['Enemy', 'Enemy'], ['Neutrality', 'Neutrality']], selected: f.object.type), include_blank: true)%>
        <% end %>



      </p>
      <p>
        <%=f.submit class: 'btn btn-dark' %>
      </p>
    <% end %>
  </section>
</article>

people/app/views/users/edit.html.erb
<h1> Edit User</h1>

<%= render 'form' %>

people/app/views/users/enemy.html.erb
<article class="people">
    <section class="people-head">
      <div class="container">
        <h2>Main page</h2>

            <%= will_paginate @enemy, :renderer => 'BootstrapPagination::Rails' %>

          <div class="row">
            <% @enemy.each do |enemy| %>
                    <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter hdpe">
                      <h2><%= link_to enemy.name, enemy_path(enemy) %></h2>
                      <br>
                      <small>
                        Type: <b><%= enemy.type %></b> <br>
                        <%= link_to 'Edit', edit_user_path(enemy), class: 'btn btn-warning' %>
                        <%= link_to 'Destroy', user_path(enemy), method: :delete, data:{confirm: 'Are you sure?'}, class: 'btn btn-danger' %><br>
                      </small>
                      <hr>
                    </div>
            <% end %>
          </div>

        <%= will_paginate @enemy, :renderer => 'BootstrapPagination::Rails' %>
        </div>
    </section>
</article>

people/app/views/users/friend.html.erb
<article class="people">
    <section class="people-head">
      <div class="container">
        <h2>Main page</h2>

            <%= will_paginate @friend, :renderer => 'BootstrapPagination::Rails' %>

          <div class="row">
            <% @friend.each do |friend| %>
                    <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter hdpe">
                      <h2><%= link_to friend.name, friend_path(friend) %></h2>
                      <br>
                      <small>
                        Type: <b><%= friend.type %></b> <br>
                        <%= link_to 'Edit', edit_user_path(friend), class: 'btn btn-warning' %>
                        <%= link_to 'Destroy', user_path(friend), method: :delete, data:{confirm: 'Are you sure?'}, class: 'btn btn-danger' %><br>
                      </small>
                      <hr>
                    </div>
            <% end %>
          </div>

        <%= will_paginate @friend, :renderer => 'BootstrapPagination::Rails' %>
        </div>
    </section>
</article>

people/app/views/users/index.html.erb
<article class="people">
    <section class="people-head">
      <div class="container">
        <h2>Main page</h2>

            <%= will_paginate @user, :renderer => 'BootstrapPagination::Rails' %>
        
          <div class="row">
            <% @user.each do |user| %>
                    <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter hdpe">
                      <h2><%= link_to user.name, user_path(user) %></h2>
                      <br>
                      <small>
                        Type: <b><%= user.type %></b> <br>
                        <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-warning' %>
                        <%= link_to 'Destroy', user_path(user), method: :delete, data:{confirm: 'Are you sure?'}, class: 'btn btn-danger' %><br>
                      </small>
                      <hr>
                    </div>
            <% end %>
          </div>

        <%= will_paginate @user, :renderer => 'BootstrapPagination::Rails' %>
        </div>
    </section>
</article>

people/app/views/users/neutrality.html.erb
<article class="people">
    <section class="people-head">
      <div class="container">
        <h2>Main page</h2>

            <%= will_paginate @neutrality, :renderer => 'BootstrapPagination::Rails' %>

          <div class="row">
            <% @neutrality.each do |neutrality| %>
                    <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter hdpe">
                      <h2><%= link_to neutrality.name, neutrality_path(neutrality) %></h2>
                      <br>
                      <small>
                        Type: <b><%= neutrality.type %></b> <br>
                        <%= link_to 'Edit', edit_user_path(neutrality), class: 'btn btn-warning' %>
                        <%= link_to 'Destroy', user_path(neutrality), method: :delete, data:{confirm: 'Are you sure?'}, class: 'btn btn-danger' %><br>
                      </small>
                      <hr>
                    </div>
            <% end %>
          </div>

        <%= will_paginate @neutrality, :renderer => 'BootstrapPagination::Rails' %>
        </div>
    </section>
</article>

people/app/views/users/new.html.erb
<article class="people">
  <section class="people-head">
    <div class="container">
      <h1> New User</h1>
      <% if @user.errors.any?  %>
         <div class="alert alert-danger">
             <h2>
               <%= pluralize(@user.errors.count, "error") %>
             </h2>
             <ul>
               <% @user.errors.full_messages.each do |msg| %>
                 <li><%= msg %></li>
               <% end %>
             </ul>
           </div>
       <% end %>

      <%= form_for User.new do |f| %>
        <p>
          <%= f.label :name %> <br>
          <%= f.text_field :name %>
        </p>
        <p>
          <%= f.hidden_field :type, :value => 'Neutrality' %>
        </p>
        <p>
          <%= f.label :Password %> <br>
          <%= f.password_field :password %>
        </p>
        <p>
          <%=f.submit class: 'btn btn-dark' %>
        </p>
      <% end %>
    </div>
  </section>
</article>