audio/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'group#index'

  resources :group do
    resources :artists
  end
  resources :group do
    resources :alboms
  end
  resources :artists do
    resources :alboms
  end
  resources :alboms do
    resources :songs
  end
  resources :geners do
    resources :alboms
  end
end

audio/app/models/albom.rb
class Albom < ApplicationRecord
  belongs_to :group
  belongs_to :artist
  belongs_to :gener
  has_many :songs
  accepts_nested_attributes_for :songs
  validates :name, presence: true
  validates :description, presence: true

  before_save :titlelize_names

    def titlelize_names
      self.name = self.name.titleize
    end
end

audio/app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :group
  has_many :alboms
  validates :name, presence: true
  validates :description, presence: true

  before_save :titlelize_names

    def titlelize_names
      self.name = self.name.titleize
    end
end

audio/app/models/gener.rb
class Gener < ApplicationRecord
  has_many :alboms
  validates :name, presence: true

  before_save :titlelize_names

    def titlelize_names
      self.name = self.name.titleize
    end
end

audio/app/models/group.rb
class Group < ApplicationRecord
  has_many :artists
  has_many :alboms

  validates :name, presence: true
  validates :description, presence: true

  before_save :titlelize_names

    def titlelize_names
      self.name = self.name.titleize
    end
end

audio/app/models/song.rb
class Song < ApplicationRecord
  belongs_to :albom, optional: true
  validates :name, presence: true

  before_save :titlelize_names

    def titlelize_names
      self.name = self.name.titleize
    end
end

audio/app/controllers/alboms_controller.rb
class AlbomsController < ApplicationController

  def index
    @albom = Albom.all
  end

  def new
    @group = params[:group_id]
    @albom = Albom.new
    @gener = Gener.all
    @albom.songs.build
  end

  def edit
    @albom = Albom.find(params[:id])
  end

  def show
    # @albom = Albom.where(id: params[:id])
    @albom = Albom.find(params[:id])
    @song = Song.where(albom_id: params[:id])

  end

  def update
    @albom = Albom.find(params[:id])
    if @albom.update(audio_params)
      redirect_to group_path(@albom.group_id)
    else
      render 'new'
    end
  end

  def destroy
      #render plain: params[:id].inspect
      Song.where(:albom_id => params[:id]).destroy_all
      @albom = Albom.find(params[:id])
      @albom.destroy
      redirect_to group_path(@albom.group_id)

  end

  def create
    Albom.transaction do
     @albom = Albom.new(audio_params)
   if @albom.save
       redirect_to group_path(params[:group_id])
     else
        render 'new'
     end
   end
  end

  private def audio_params
      params.require(:albom).permit(:name, :description, :image, :group_id, :artist_id, :gener_id, songs_attributes: [:name])
  end

end

audio/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController


    def index
      @artist = Artist.all
    end

    def new
      @group = params[:group_id]
      @artist = Artist.new
    end

    def edit
      @artist = Artist.find(params[:id])
    end

    def show
      @artist = Artist.where(id: params[:id])


    end

    def update
      @artist = Artist.find(params[:id])
      if @artist.update(project_params)
        redirect_to group_path(@artist.group_id)
      else
        render 'new'
      end
    end

    def destroy
      Artist.transaction do
        @artist = Artist.find(params[:id])
        @artist.destroy
      end
        redirect_to group_path(@artist.group_id)
    end

    def create
      #render plain: params[:artist].inspect
      Artist.transaction do
        @artist = Artist.new(project_params)
        if @artist.save
          redirect_to group_path(@artist.group_id)
        else
          render 'new'
        end
      end
    end

    private def project_params
        params.require(:artist).permit(:name, :description, :image, :group_id)
    end


end

audio/app/controllers/geners_controller.rb
class GenersController < ApplicationController

  def index
    @gener = Gener.all
  end
  def new
    @gener = Gener.new
  end

  def show
    @gener = Gener.find(params[:id])
  end

  def create
    Gener.transaction do
     @gener = Gener.new(audio_params)
   if @gener.save
       redirect_to group_index_path
     else
        render 'new'
     end
   end
  end

  private def audio_params
      params.require(:gener).permit(:name)
  end

end

audio/app/controllers/group_controller.rb
class GroupController < ApplicationController
  def index

    @group = Group.all
    # @group = Group.joins(:photo).select("sum(rating) / COUNT(photo_id)  as rating, photo_id as photo_id, meme_id as meme_id").order("rating DESC").group("meme_id")
#
  end
  def new
    @group = Group.new
  end
  def edit
    @group = Group.find(params[:id])
  end
  def show
    @group = Group.find(params[:id])
    @artist = Artist.where(group_id: params[:id])
    @albom = Albom.joins(:gener).select("alboms.id as aid, alboms.name as aname, alboms.description, alboms.image, geners.name").where(group_id: params[:id])
    # @albom = Albom.where(group_id: params[:id])
    # @gener = Gener.joins(:alboms).where(group_id: params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(project_params)
      redirect_to group_index_path
    else
      render 'new'
    end
  end

  def destroy
    Group.transaction do
      @group = Group.find(params[:id])
      @group.destroy
    end
    redirect_to group_index_path
  end

  def create
    Group.transaction do
      @group = Group.new(project_params)
      if @group.save
        redirect_to @group
      else
        render 'new'
      end
    end
  end

  private def project_params
			params.require(:group).permit(:name, :description, :image)
	end
end

audio/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @song = Song.all
  end

  def new
    @albom = params[:albom_id]
    @song = Song.new

  end

  def edit
    @song = Song.find(params[:albom_id])
  end

  def show
    # @albom = Albom.where(id: params[:id])
    @albom = Albom.find(params[:id])
    @song = Song.where(albom_id: params[:id])

  end

  def update
    @song = Song.find(params[:albom_id])
    if @song.update(audio_params)
      redirect_to albom_path(@song.albom_id)
    else
      render 'new'
    end
  end

  def create
    Song.transaction do
     @song = Song.new(audio_params)
     if @song.save
       redirect_to albom_path(@song.albom_id)
     else
        render 'new'
     end
   end
  end

  def destroy
    Song.transaction do
      @song = Song.find(params[:albom_id])
      @song.destroy
    end
    redirect_to albom_path(params[:id])
  end

  private def audio_params
      params.require(:song).permit(:name, :podcast, :albom_id)
  end
end

audio/app/helpers/albom_helper.rb
module AlbomHelper
end

audio/app/helpers/artist_helper.rb
module ArtistHelper
end

audio/app/helpers/geners_helper.rb
module GenersHelper
end

audio/app/helpers/group_helper.rb
module GroupHelper
end

audio/app/helpers/song_helper.rb
module SongHelper
end

audio/app/views/songs/_form.html.erb
  <article class="audio">
    <section class="audio-head">
      Albom: <b><%= @albom %></b> <br>

      <%= simple_form_for @song, html: {multipart: true}, url: albom_songs_path do |f| %>
      <p>
        Name <br>
        <%=f.text_field :name %>
      </p>

      <p>
        Image <br>
        <%=f.file_field :podcast %>
      </p>
        <%= f.hidden_field :albom_id, :value => @albom %>
        <p>
        <%=f.submit class: 'btn btn-dark' %>
      </p>
      <% end %>
    </section>
  </article>

audio/app/views/songs/edit.html.erb
<h2>Edit Albom</h2>

  <article class="audio">
    <section class="audio-head">
      <% if @song.errors.any?  %>
             <div class="alert alert-danger">
                 <h2>
                   <%= pluralize(@song.errors.count, "error") %> 
                 </h2>
                 <ul>
                   <% @song.errors.full_messages.each do |msg| %>
                     <li><%= msg %></li>
                   <% end %>
                 </ul>
               </div>
           <% end %>

      <%= simple_form_for @song, html: {multipart: true}, url: albom_song_path(@song), method: :patch do |f| %>
      <p>
        Name <br>
        <%=f.text_field :name %>
      </p>

      <p>
        Image <br>
        <%=f.file_field :podcast %>
      </p>

        <p>
        <%=f.submit class: 'btn btn-dark' %>
      </p>
      <% end %>
    </section>
  </article>

audio/app/views/songs/index.html.erb
<h2>song</h2>
<article class="audio">
    <section class="audio-head">
      <div class="container">
        <div class="row">
        </div>
      </div>
    </section>
</article>

audio/app/views/songs/new.html.erb
<h2>New song</h2>


<% if @song.errors.any?  %>
       <div class="alert alert-danger">
           <h2>
             <%= pluralize(@song.errors.count, "error") %> 
           </h2>
           <ul>
             <% @song.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
     <% end %>

<%= render 'form' %>