memes/config/routes.rb
Rails.application.routes.draw do

  root 'memes#index'
  #get 'about' => 'memes#about'
  resources :memes do
    resources :photos
  end

  resources :photos do
    resources :votings
  end

  get "meme_out" => "sessions#destroy", :as => "meme_out"
  get "new_meme_in" => "sessions#create", :as => "new_meme_in"
  resources :sessions

end

memes/app/models/meme.rb
class Meme < ApplicationRecord
  # has_one_attached :image
  has_many :photo
  mount_uploader :image, ImageUploader
  validates :title, presence: true, length: {minimum: 3}
  validates :description, presence: true, length: {minimum: 10}
  validates :author, presence: true, length: {minimum: 3}
  validates :image, presence: true

  def self.search(params)
    meme = all
    meme = meme.where("author LIKE ?", "%#{params[:search]}%") if params[:search]
    meme

    # if (search)
    #   where (["author LIKE ?", "%#{search}%"])
    #
    # else
    #   paginate :page => @page, :per_page => 8
    # end

  end

end

memes/app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :meme
  has_many :voting
  mount_uploader :image, ImageUploader
  validates :image, presence: true


end

memes/app/models/voting.rb
class Voting < ApplicationRecord
  belongs_to :photo
  validates :rating, presence: true
end

memes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger, :info, :warning
#  rescue_form User::NotAuthorized, with: :user_not_authorized

  # private def user_not_authorized
  #   flash[:error] = 'You shoud authorized'
  #   redirect_back(fallback_location: root_path)
  # end

end

memes/app/controllers/memes_controller.rb
class MemesController < ApplicationController
  # before_action :check_authorization

  def index
       @meme = Meme.search(params).paginate(page: params[:page], per_page: 9)

     # if params[:search]
     #   @meme = Meme.search(params[:search])
     # else
     #    @meme = Meme.paginate(page: params[:page], per_page: 8)
     #  end
    @statisticVoting = Voting.joins(:photo).select("sum(rating) / COUNT(photo_id)  as rating, photo_id as photo_id, meme_id as meme_id").order("rating DESC").group("meme_id")
#    @statisticVoting = Voting.left_outer_joins(photo: :meme).select("sum(rating) / COUNT(photo_id)  as rating, photo_id as photo_id, meme_id as meme_id, title, description, author, meme::image").order("rating DESC").group("meme_id")
#    @statisticVoting = Voting.joins(photo: :meme).select("sum(rating) / COUNT(photo_id)  as rating, photo_id as photo_id, meme_id as meme_id, title, description, author, meme::image").order("rating DESC").group("meme_id")
#    @statisticVoting = Voting.left_outer_joins(photo: :meme).select("sum(rating) / COUNT(photo_id)  as rating, photo_id, meme_id, title, description, author, meme::image").order("rating DESC").group("meme_id")
    # @statisticVoting = Voting.select("count(photo_id) as count_photo_id, sum(rating) as rating, photo_id").group("photo_id")
    # @statisticPhoto = Photo.all

  end

  def about
  end

  def new
    @meme = Meme.new
  end

  def edit
      @meme = Meme.find(params[:id])
  end


  def show
    @meme = Meme.find(params[:id])
  end

  def create
    @meme = Meme.new(meme_params)
    if @meme.save

      redirect_to new_meme_in_path(author: meme_params[:author])
      #redirect_to memes_path, success: 'Create new meme'
    else
      render :new
    end
  end

  def update
    @meme = Meme.find(params[:id])
    if @meme.update(meme_params)
     redirect_to memes_path, success: 'Update success'
    else
      render :edit, danger: 'Update bad'
    end
  end

  def destroy
    @meme = Meme.find(params[:id])
    @meme.destroy
    redirect_to memes_path, info: 'Delete success'
  end

  private def meme_params
    params.require(:meme).permit(:title, :description, :image, :author)
  end

  # def check_authorization
  #   raise User::NotAuthorization unless current_user.admin?
  # end
end

memes/app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photo = Photo.all
  end

  def show
    @photo = Photo.find(params[:meme_id])
    #@voting = Voting.find(params[:meme_id])
  end

  def create
    @meme = Meme.find(params[:meme_id])
    @photo = @meme.photo.create(photo_params)
    redirect_to meme_path(@meme)
  end

  def update
    @meme = Meme.find(params[:meme_id])
    @photo = @meme.photo.create(photo_params)
    redirect_to meme_path(@meme)
  end

  def destroy
    @photo = Photo.find(params[:meme_id])
    @photo.destroy
    redirect_to meme_path(@photo.meme_id)
end

  private def photo_params
    params.require(:photo).permit(:image)
  end

end

memes/app/controllers/search_controller.rb
class SearchController < ApplicationController

  
end

memes/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    session[:name] = params[:author]
    redirect_to memes_path, success: 'Create new meme'
  end

  def destroy
    session[:name] = nil
    redirect_to memes_path
  end
end

memes/app/controllers/votings_controller.rb
class VotingsController < ApplicationController


  def index
    @voting = Voting.all
  end

  def show
    @voting = Voting.find(params[:id])
  end

  def create
    @photo = Photo.find(params[:photo_id])
    @voting = @photo.voting.create(voting_params)
    redirect_to meme_path(@photo.meme_id)
  end

  # def update
  #   @photo = Photo.find(params[:photo_id])
  #   @voting = @photo.voting.create(voting_params)
  #   redirect_to memes_path
  # end

  private def voting_params
    params.require(:voting).permit(:rating)
  end
end

memes/app/helpers/memes_helper.rb
module MemesHelper
end

memes/app/helpers/photos_helper.rb
module PhotosHelper
end

memes/app/helpers/search_helper.rb
module SearchHelper
end

memes/app/helpers/votings_helper.rb
module VotingsHelper
end

memes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-light bg-faded">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to 'Main', memes_url, class: 'btn btn-outline-primary pull-xs-right' %>
            <%= link_to 'New meme', new_meme_path, class: 'btn btn-outline-primary pull-xs-right' %>

            <% if session[:name] %>
              Last add: <%= link_to session[:name] , meme_out_path %>   .
             <% else %>
              Update was not long ago
             <% end %>
          </li>
        </ul>
        <%= form_tag memes_path, class: 'form-inline my-2 my-lg-0', :method => 'get' do %>
            <%= text_field_tag :search, params[:search], placeholder: 'Search', class: 'form-control mr-sm-2' %>
            <%= submit_tag "Search", class: 'btn btn-outline-success my-2 my-sm-0', :name => nil %>
        <% end %>
      </nav>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name,message| %>
            <div class="alert alert-<%= name %>">
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>