team/config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

	# root 'commands#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
	get "log_in" => "sessions#new", :as => "log_in"
	get "sign_up" => "users#new", :as => "sign_up"
	get "account/:id" => "users#edit", :as => "account"

  get 'sessions/new'
  root :to => "sessions#new"
	resources :sessions

	resources :commands do
		resources :users
	end

	resources :users

	resources :search

  end

team/app/models/command.rb
class Command < ApplicationRecord
	# before_action :authenticate_user!
	has_many :user
	validates :name, uniqueness: true

	def self.search(params)
		command = all
		command = command.where("name LIKE ?", "%#{params[:search]}%") if params[:search]
		command
	end


end

team/app/models/user.rb
class User < ApplicationRecord
# has_secure_password
belongs_to :command

  def self.search(params)
		user = all
		user = user.where("name LIKE ?", "%#{params[:search]}%") if params[:search]
		user
	end

  def self.authenticate(name, password)
		user = find_by_name(name)
		if user && user.password == password
      user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password = password
		end
	end


end

team/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

	private

	def current_user
	  @current_user ||= User.find(session[:id]) if session[:id]
	end



  protected def authenticate_user!
     unless current_user
     store_location_for(:user, request.url)
     redirect_to new_session_url
   end
 end
end

team/app/controllers/commands_controller.rb
class CommandsController < ApplicationController
before_action :authenticate_user!
	def index
		#@command = Command.search(params).paginate(page: params[:page], per_page: 9)
		@command = Command.search(params).paginate(page: params[:page], per_page: 9)
	end

	def show
		@command = Command.find(params[:id])
	end

	def edit
		@command = Command.find(params[:id])
	end

	def new
		@command = Command.new
	end

	def create
		@command = Command.new(command_params)
		if @command.save
			redirect_to commands_path, success: 'Create new meme'
		#redirect_to memes_path,
		else
			render :new
		end
	end

	def update
		@command = Command.find(params[:id])
		if @command.update(command_params)
			redirect_to commands_path, success: 'Update success'
		else
			render :edit, danger: 'Update bad'
		end
	end

	def destroy
		@command = Command.find(params[:id])
		@command.destroy
		redirect_to commands_path, info: 'Delete success'
	end


	private def command_params
		params.require(:command).permit(:name, :region)
	end

end

team/app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
	
	#def
	#	@search = Command.new_search(params[:serach])
#		@search.condition.field_starts_with = 
#		@command = @search.all
#	end
	
	def index
	end
	
	def show
	end

end

team/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
	  user = User.authenticate(params[:name], params[:password])
	  if user
		session[:id] = user.id
		redirect_to commands_url, :notice => "Logged in!"
	  else
		flash.now.alert = "Invalid first_name or password"
		render 'new'
	  end
	end

	def destroy
		session[:id] = nil
		redirect_to root_url, :notice => "Logged out!"

	end


end

team/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
	def index
		#@command = Command.search(params).paginate(page: params[:page], per_page: 9)
		@user = User.search(params).paginate(page: params[:page], per_page: 12)
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:command_id])
		@command = Command.all
	end

	def new
		@user = User.new
		@command = Command.all
	end




	def create

#		render plain: params[:user].inspect
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to commands_path, success: 'Update success'
		else
			render :edit, danger: 'Update bad'
		end
	end

	def destroy
		@user = User.find(params[:command_id])
		@user.destroy
		redirect_to command_path(params[:id]), info: 'Delete success'
	end


	def user_params
      params.require(:user).permit(:name, :phone, :male, :command_id, :password)
    end
end

team/app/helpers/commands_helper.rb
module CommandsHelper
end

team/app/helpers/searchs_helper.rb
module SearchsHelper
end

team/app/views/commands/_form.html.erb
<article class="team">
	<section class="team-head">
		<%= form_for @command do |f| %>
			<% if @command.errors.any?  %>
				<div class="alert alert-danger">
					<h2>
						<%= pluralize(@command.errors.count, "error") %> prohibited
						Command from being saved:
					</h2>
					<ul>
						<% @command.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

			<p>
				<%= f.label :name %> <br>
				<%= f.text_field :name %>
			</p>
			<p>
				<%= f.label :region %> <br>
				<%=f.text_field :region %>
			</p>
			<p>
				<%=f.submit class: 'btn btn-dark' %>
			</p>
		<% end %>
	</section>
</article>

team/app/views/commands/edit.html.erb
<h3> Edit command</h3>

<%= render 'form' %>

team/app/views/commands/index.html.erb
		<div class="container">
			<nav class="navbar navbar-light bg-faded">
				<ul class="navbar-nav">
					<li class="nav-item active">
						<h2>Command page</h2>	
					</li>
				</ul>
				
				<%= form_tag commands_path, class: 'form-inline my-2 my-lg-0', :method => 'get' do %>
					<%= text_field_tag :search, params[:search], placeholder: 'Search', class: 'form-control mr-sm-2' %>
					<%= submit_tag "Search", class: 'btn btn-outline-secondary my-2 my-sm-0', :name => nil %>
				<% end %>
			</nav>
		</div>	
<article class="team">
    <section class="team-head">

        <%= will_paginate @command, :renderer => 'BootstrapPagination::Rails' %>


		<div class="container">
			<div class="row">
				<% @command.each do |command| %>
					<div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter hdpe">
						<h2><%= link_to command.name, command_path(command) %></h2>

					   
						<br>
						<small>
						  Region: <b><%= command.region %></b> <br>
						  <%= link_to 'Edit', edit_command_path(command), class: 'btn btn-warning' %>
						  <%= link_to 'Destroy', command_path(command), method: :delete, data:{confirm: 'Are you sure?'}, class: 'btn btn-danger' %><br>
						</small>
						<hr>
					</div>
				
				<% end %>     

			</div>
		</div>
		<%= will_paginate @command, :renderer => 'BootstrapPagination::Rails' %>
    </section>
</article>

team/app/views/commands/new.html.erb
<h3> New command</h3>

<%= render 'form' %>

team/app/views/commands/show.html.erb
<h4>User in command</h4>
<article class="team">
    <section class="team-head">
		<h2><%= @command.name %></h2>
			
				
		<div class="container">
			<div class="row">
				<% @command.user.each do |user| %>
					<div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter hdpe">
						<h2><%= link_to user.name, command_user_path(user.id) %></h2>
						<br>
						<small>
							Phome: <b><%= user.phone %></b> <br>
							Male: <b><%= user.male %></b> <br>
							<%= link_to 'Edit', edit_command_user_path(user.id), class: 'btn btn-warning' %>
							<%= link_to 'Destroy', command_user_path(user.id), method: :delete, data:{confirm: 'Are you sure?'}, class: 'btn btn-danger' %><br>
						</small>
						<hr>
					</div>
				<% end %>     
			</div>
		</div>
    </section>
</article>

team/app/views/users/_form.html.erb
<article class="team">
	<section class="team-head">
		<%= form_for @user do |f| %>
			<% if @user.errors.any?  %>
				<div class="alert alert-danger">
					<h2>
						<%= pluralize(@user.errors.count, "error") %> prohibited
						User from being saved:
					</h2>
					<ul>
						<% @user.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

			<p>
				<%= f.label :name %> <br>
				<%= f.text_field :name %>
			</p>
			<p>
				<%= f.label :phone %> <br>
				<%=f.text_field :phone %>
			</p>
			<p>
				<%= f.label :male %> <br>
				<%=f.text_field :male %>
			</p>
			<p>
				<%= f.collection_select :command_id, @command, :id, :name, {include_blank: 'Please Select'}%>
			</p>
			<p>
				<%= f.label :password %> <br>
				<%=f.password_field :password %>
			</p>
			<p>
				<%=f.submit class: 'btn btn-dark' %>
			</p>
		<% end %>
	</section>
</article>

team/app/views/users/edit.html.erb
<h3> Edit user</h3>

<%= render 'form' %>

team/app/views/users/index.html.erb
		<div class="container">
			<nav class="navbar navbar-light bg-faded">
				<ul class="navbar-nav">
					<li class="nav-item active">
						<h2>User page</h2>	
					</li>
				</ul>
				
				<%= form_tag users_path, class: 'form-inline my-2 my-lg-0', :method => 'get' do %>
					<%= text_field_tag :search, params[:search], placeholder: 'Search', class: 'form-control mr-sm-2' %>
					<%= submit_tag "Search", class: 'btn btn-outline-secondary my-2 my-sm-0', :name => nil %>
				<% end %>
			</nav>
		</div>	
<article class="team">
    <section class="team-head">
				
        <%= will_paginate @user, :renderer => 'BootstrapPagination::Rails' %>

		<div class="container">
			<div class="row">
				<% @user.each do |user| %>
					<div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter hdpe">
						<h2><%= link_to user.name, user_path(user) %></h2>
						<br>
						<small>
							Phone: <b><%= user.phone %></b> <br>
							Male: <b><%= user.male %></b> <br>
							
							
							<%= link_to 'Destroy', user_path(user), method: :delete, data:{confirm: 'Are you sure?'}, class: 'btn btn-danger' %><br>
						</small>
						<hr>
					</div>
				
				<% end %>     

			</div>
		</div>
		<%= will_paginate @user, :renderer => 'BootstrapPagination::Rails' %>
    </section>
</article>

team/app/views/users/new.html.erb
<h3> New user</h3>

<%= render 'form' %>